import { type AssetKind, GROUP_FOR_KIND, kindFor } from './kinds.ts';

export type ManifestEntry = {
	group: string;
	key: string;
	kind: AssetKind;
	path: string;
};

export type ManifestPlan = {
	entries: ManifestEntry[];
	/** Files found under assets/ whose extension maps to no asset kind. */
	ignored: string[];
};

/** `ui/buttons/play.png` becomes `ui_buttons_play`. */
export function keyFor(relativePath: string): string {
	const withoutExtension = relativePath.replace(/\.[^./]+$/, '');

	const key = withoutExtension
		.replace(/[^a-zA-Z0-9]+/g, '_')
		.replace(/^_+|_+$/g, '')
		.replace(/_{2,}/g, '_');

	return /^[0-9]/.test(key) ? `_${key}` : key;
}

export function planManifest(relativePaths: string[]): ManifestPlan {
	const entries: ManifestEntry[] = [];
	const ignored: string[] = [];
	const seen = new Map<string, string>();

	for (const path of [...relativePaths].sort()) {
		const kind = kindFor(path);

		if (!kind) {
			ignored.push(path);
			continue;
		}

		const group = GROUP_FOR_KIND[kind];
		const key = keyFor(path);
		const slot = `${group}.${key}`;

		const clash = seen.get(slot);
		if (clash) {
			throw new Error(`Assets "${clash}" and "${path}" both map to ${slot}. Rename one of them.`);
		}

		seen.set(slot, path);
		entries.push({ group, key, kind, path });
	}

	return { entries, ignored };
}

export function renderManifest(plan: ManifestPlan, assetsDirectory = 'assets'): string {
	const groups = new Map<string, ManifestEntry[]>();

	for (const entry of plan.entries) {
		const bucket = groups.get(entry.group) ?? [];
		bucket.push(entry);
		groups.set(entry.group, bucket);
	}

	const body = [...groups.entries()]
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([group, entries]) => {
			const fields = entries
				.map(
					(entry) =>
						`\t\t${entry.key}: { kind: '${entry.kind}', path: '${assetsDirectory}/${entry.path}' },`,
				)
				.join('\n');

			return `\t${group}: {\n${fields}\n\t},`;
		})
		.join('\n');

	return [
		'// Generated by kreb from the assets directory. Do not edit.',
		'',
		"import type { AssetRef } from 'kreb';",
		'',
		`export const Assets = {\n${body}\n} as const satisfies Record<string, Record<string, AssetRef>>;`,
		'',
	].join('\n');
}
