import type { Plan, PlannedFunction } from './plan.ts';
import { HANDLE_STRUCTS } from './typemap.ts';

const PREAMBLE = `// Generated by tools/codegen. Do not edit.

#include "kreb_color.h"
#include <raylib.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

static inline Matrix kreb_matrix_from_floats(const float *m) {
    Matrix out;
    memcpy(&out, m, sizeof(Matrix));
    return out;
}

void kreb_free(void *handle) {
    free(handle);
}
`;

function cReturnType(fn: PlannedFunction): string {
	switch (fn.returnInfo.kind) {
		case 'void':
			return 'void';
		case 'scalar':
			return fn.returnInfo.c;
		case 'cstring':
			return 'const char *';
		case 'color':
			return 'uint32_t';
		case 'handle':
		case 'pointer':
		case 'callback':
			return 'void *';
		default:
			return 'void';
	}
}

function declare(type: string, name: string): string {
	return type.endsWith('*') ? `${type}${name}` : `${type} ${name}`;
}

function signature(fn: PlannedFunction): string {
	const parts = fn.parameters.flatMap((p) => p.flat.map((f) => declare(f.c, f.name)));
	if (fn.outComponents) parts.push('float *kreb_out');

	const declarator = declare(cReturnType(fn), fn.shimName);
	return `${declarator}(${parts.length ? parts.join(', ') : 'void'})`;
}

function body(fn: PlannedFunction): string {
	const args = fn.parameters.map((p) => p.argument).join(', ');
	const call = `${fn.name}(${args})`;

	switch (fn.returnInfo.kind) {
		case 'void':
			return `    ${call};`;

		case 'scalar':
			return `    return (${fn.returnInfo.c})${call};`;

		case 'cstring':
			return `    return ${call};`;

		case 'color':
			return `    return kreb_color_to_rgba(${call});`;

		case 'pointer':
		case 'callback':
			return `    return (void *)${call};`;

		case 'handle': {
			const type = fn.returnInfo.struct;
			return [
				`    ${type} *kreb_result = (${type} *)malloc(sizeof(${type}));`,
				`    *kreb_result = ${call};`,
				`    return kreb_result;`,
			].join('\n');
		}

		case 'matrix':
			return [
				`    Matrix kreb_value = ${call};`,
				`    memcpy(kreb_out, &kreb_value, sizeof(Matrix));`,
			].join('\n');

		case 'value': {
			const struct = fn.returnInfo.struct;
			return [
				`    ${struct.name} kreb_value = ${call};`,
				`    ${struct.decompose('kreb_value', 'kreb_out')}`,
			].join('\n');
		}

		default:
			return `    ${call};`;
	}
}

/**
 * Allocators let JavaScript build a heap struct before raylib fills it in,
 * which is what functions taking a mutable handle (UpdateCamera) require.
 */
function allocators(): string {
	return [...HANDLE_STRUCTS]
		.map(
			(name) =>
				`void *kreb_alloc_${name}(void) {\n` +
				`    ${name} *kreb_result = (${name} *)calloc(1, sizeof(${name}));\n` +
				`    return kreb_result;\n}`,
		)
		.join('\n\n');
}

export function emitC(plan: Plan): string {
	const functions = plan.functions.map((fn) => `${signature(fn)} {\n${body(fn)}\n}`).join('\n\n');

	return `${PREAMBLE}\n${allocators()}\n\n${functions}\n`;
}
