import {
	type Accessor,
	emitAccessorsSymbols,
	emitWritersSymbols,
	type Writer,
} from './accessors.ts';
import type { ApiDefine, ApiEnum } from './api.ts';
import type { Plan, PlannedFunction, PlannedParam } from './plan.ts';
import { ffiReturnType, HANDLE_STRUCTS } from './typemap.ts';

const HEADER = '// Generated by tools/codegen. Do not edit.\n';

function scalarTsType(raw: string, ffi: string): string {
	if (raw === 'bool') return 'boolean';
	return ffi === 'i64' ? 'bigint' : 'number';
}

function tsParamType(param: PlannedParam): { name: string; type: string }[] {
	switch (param.info.kind) {
		case 'scalar':
			return [{ name: param.name, type: scalarTsType(param.info.raw, param.info.ffi) }];
		case 'cstring':
			return [{ name: param.name, type: 'string' }];
		case 'color':
			return [{ name: param.name, type: 'number' }];
		case 'handle':
		case 'pointer':
		case 'callback':
			return [{ name: param.name, type: 'Pointer' }];
		case 'matrix':
			return [{ name: param.name, type: 'Float32Array' }];
		case 'value':
			return param.flat.map((f) => ({ name: f.name, type: 'number' }));
		default:
			return [];
	}
}

function tsArgument(param: PlannedParam): string[] {
	switch (param.info.kind) {
		case 'scalar':
			return [param.info.raw === 'bool' ? `${param.name} ? 1 : 0` : param.name];
		case 'cstring':
			return [`cstring(${param.name})`];
		case 'matrix':
			return [`ptr(${param.name})`];
		case 'value':
			return param.flat.map((f) => f.name);
		default:
			return [param.name];
	}
}

function tsReturnType(fn: PlannedFunction): string {
	switch (fn.returnInfo.kind) {
		case 'void':
			return 'void';
		case 'scalar':
			return scalarTsType(fn.returnInfo.raw, fn.returnInfo.ffi);
		case 'cstring':
			return 'string';
		case 'color':
			return 'number';
		case 'handle':
		case 'pointer':
		case 'callback':
			return 'Pointer | null';
		case 'value':
		case 'matrix':
			return 'Float32Array';
		default:
			return 'void';
	}
}

function emitFunction(fn: PlannedFunction): string {
	const signature = fn.parameters
		.flatMap(tsParamType)
		.map((p) => `${p.name}: ${p.type}`)
		.join(', ');

	const args = fn.parameters.flatMap(tsArgument);
	const returnType = tsReturnType(fn);

	if (fn.outComponents) {
		const size = fn.outComponents.length;
		const call = [...args, 'scratchPtr'].join(', ');
		return [
			`export function ${fn.name}(${signature}): ${returnType} {`,
			`\tsymbols().${fn.shimName}(${call});`,
			`\treturn scratch.slice(0, ${size});`,
			'}',
		].join('\n');
	}

	const call = `symbols().${fn.shimName}(${args.join(', ')})`;

	const returned = (() => {
		switch (fn.returnInfo.kind) {
			case 'void':
				return `\t${call};`;
			case 'scalar':
				return fn.returnInfo.raw === 'bool' ? `\treturn ${call} === 1;` : `\treturn ${call};`;
			case 'cstring':
				return `\treturn readCString(${call});`;
			default:
				return `\treturn ${call};`;
		}
	})();

	return [`export function ${fn.name}(${signature}): ${returnType} {`, returned, '}'].join('\n');
}

function emitSymbols(plan: Plan, accessors: Accessor[], writers: Writer[]): string {
	const entries = plan.functions.map((fn) => {
		const args = fn.parameters.flatMap((p) => p.flat.map((f) => `'${f.ffi}'`));
		if (fn.outComponents) args.push(`'ptr'`);

		return `\t${fn.shimName}: { args: [${args.join(', ')}], returns: '${ffiReturnType(fn.returnInfo)}' },`;
	});

	const allocators = [...HANDLE_STRUCTS].map(
		(name) => `\tkreb_alloc_${name}: { args: [], returns: 'ptr' },`,
	);

	return [
		'const shimSymbols = {',
		`\tkreb_free: { args: ['ptr'], returns: 'void' },`,
		...allocators,
		...emitAccessorsSymbols(accessors),
		...emitWritersSymbols(writers),
		...entries,
		'} satisfies Record<string, FFIFunction>;',
	].join('\n');
}

export function emitBindings(
	plan: Plan,
	accessors: Accessor[] = [],
	writers: Writer[] = [],
): string {
	const scratchSize = Math.max(16, ...plan.functions.map((fn) => fn.outComponents?.length ?? 0));

	return [
		HEADER,
		`import { type FFIFunction, type Pointer, CString, ptr } from 'bun:ffi';`,
		`import { loadShim } from '@kreb/raylib-sys/loader';`,
		'',
		`export const SHIM_NAME = 'kreb_raylib';`,
		'',
		emitSymbols(plan, accessors, writers),
		'',
		'type Symbols = ReturnType<typeof loadShim<typeof shimSymbols>>;',
		'',
		'let cached: Symbols | null = null;',
		'',
		'// Loaded on first call rather than at import, so importing kreb never',
		'// requires a built shim and callers need no dynamic import dance.',
		'export function symbols(): Symbols {',
		'\tcached ??= loadShim(SHIM_NAME, shimSymbols);',
		'\treturn cached;',
		'}',
		'',
		`const scratch = new Float32Array(${scratchSize});`,
		'const scratchPtr = ptr(scratch);',
		'const encoder = new TextEncoder();',
		'',
		'function cstring(text: string): Uint8Array {',
		"\treturn encoder.encode(text + '\\0');",
		'}',
		'',
		'function readCString(pointer: Pointer | null): string {',
		"\treturn pointer === null ? '' : new CString(pointer).toString();",
		'}',
		'',
		'export function free(handle: Pointer): void {',
		'\tsymbols().kreb_free(handle);',
		'}',
		'',
		...plan.functions.map(emitFunction),
		'',
	].join('\n');
}

export function emitEnums(enums: ApiEnum[]): string {
	const blocks = enums.map((definition) => {
		const values = definition.values.map((entry) => `\t${entry.name}: ${entry.value},`).join('\n');

		return [
			`export const ${definition.name} = {`,
			values,
			'} as const;',
			'',
			`export type ${definition.name} = (typeof ${definition.name})[keyof typeof ${definition.name}];`,
		].join('\n');
	});

	return [HEADER, ...blocks, ''].join('\n');
}

const COLOR_LITERAL = /\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\}/;

export function emitColors(defines: ApiDefine[]): string {
	const colors = defines.filter((define) => define.type === 'COLOR');

	const entries = colors.flatMap((define) => {
		const match = COLOR_LITERAL.exec(String(define.value));
		if (!match) return [];

		const [, r, g, b, a] = match;
		const packed = ((Number(r) << 24) | (Number(g) << 16) | (Number(b) << 8) | Number(a)) >>> 0;

		return [`export const ${define.name} = 0x${packed.toString(16).padStart(8, '0')};`];
	});

	return [HEADER, ...entries, ''].join('\n');
}
